name: Build and container scan 

on: workflow_dispatch 

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: orders
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: download java tracer
        run: wget --no-check-certificate  -O dd-java-agent.jar 'https://github.com/DataDog/dd-trace-java/releases/download/v0.91.0/dd-java-agent.jar'

      - run: docker build . -f docker/orders/Dockerfile.github -t acrforctooffice.azurecr.io/orders:${{ github.sha }}
        
      - uses: Azure/container-scan@v0
        name: Scan image for vulnerabilities
        id: container-scan
        continue-on-error: true      
        with:
          image-name: acrforctooffice.azurecr.io/orders:${{ github.sha }}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Login to ACR'
        run: az acr login --name acrforctooffice

      - run: docker push acrforctooffice.azurecr.io/orders:${{ github.sha }}

      - name: Post logs to appinsights
        uses: Azure/publish-security-assessments@v0
        with: 
          scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}       


